// Code generated by "stringer -type=GameType"; DO NOT EDIT.

package sports

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Basketball-1]
	_ = x[Tennis-2]
}

const _GameType_name = "UnknownBasketballTennis"

var _GameType_index = [...]uint8{0, 7, 17, 23}

func (i GameType) String() string {
	if i < 0 || i >= GameType(len(_GameType_index)-1) {
		return "GameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameType_name[_GameType_index[i]:_GameType_index[i+1]]
}
